version: '3.8'

services:
  vacation-service:
    build: .
    container_name: vacation-service
    ports:
      - 8080:8080
      - 12201:12201
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - postgresql

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8081:8080
    environment:
      - SWAGGER_JSON=/swagger.json
    volumes:
      - ./swagger/vacation_api/v1/vacation_api.swagger.json:/swagger.json
    networks:
      - postgresql

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgresql
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgresql
    restart: unless-stopped

networks:
  postgresql:
    driver: bridge

volumes:
  postgres:
  pgadmin:
