version: '3.1'

services:
  postgres:
    image: postgres
    container_name: vacation_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: vacationdb
    volumes:
     - ./postgres:/var/lib/postgresql/data/
    ports:
     - 5432:5432

volumes:
  postgres_data:
    driver: local